# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"

  Server = "lforgionS"
  config.vm.define Server do |node|
    node.vm.hostname = Server
    node.vm.network "private_network", ip: "192.168.56.110"

    node.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = Server
    end

    node.vm.provision "shell", path: "scripts/setup_server.sh"
  end
end